package igraphic;

import javax.swing.JOptionPane;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author aBSi
 */
public class Presentation extends javax.swing.JFrame {
public static String holder ="";
    /**
     * Creates new form Presentation
     */
    public Presentation() {
        initComponents();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jOptionPane1 = new javax.swing.JOptionPane();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        mainInput = new javax.swing.JTextField();
        btClear = new javax.swing.JButton();
        btDel = new javax.swing.JButton();
        btSave = new javax.swing.JButton();
        btQuit = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        bt0 = new javax.swing.JButton();
        bt1 = new javax.swing.JButton();
        bt2 = new javax.swing.JButton();
        bt3 = new javax.swing.JButton();
        bt4 = new javax.swing.JButton();
        bt5 = new javax.swing.JButton();
        bt6 = new javax.swing.JButton();
        bt7 = new javax.swing.JButton();
        bt8 = new javax.swing.JButton();
        bt9 = new javax.swing.JButton();
        bt00 = new javax.swing.JButton();
        btrst = new javax.swing.JButton();
        btPlus = new javax.swing.JButton();
        btMinus = new javax.swing.JButton();
        btX = new javax.swing.JButton();
        btratio = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(null);
        setMinimumSize(new java.awt.Dimension(375, 410));
        setPreferredSize(new java.awt.Dimension(370, 400));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Stencil Std", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 204, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("SUP'INFO");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel2.setOpaque(true);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(140, 330, 80, 20);

        jLabel3.setFont(new java.awt.Font("Adobe Garamond Pro Bold", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("CALCULATRICE");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 20, 300, 60);

        mainInput.setEditable(false);
        mainInput.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        mainInput.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        mainInput.setToolTipText("");
        mainInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainInputActionPerformed(evt);
            }
        });
        mainInput.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                mainInputKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                mainInputKeyReleased(evt);
            }
        });
        getContentPane().add(mainInput);
        mainInput.setBounds(20, 70, 320, 50);

        btClear.setText("C");
        btClear.setName("C"); // NOI18N
        btClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btClearActionPerformed(evt);
            }
        });
        getContentPane().add(btClear);
        btClear.setBounds(20, 140, 75, 23);

        btDel.setText("Supr");
        btDel.setMinimumSize(new java.awt.Dimension(41, 23));
        btDel.setName("del"); // NOI18N
        btDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDelActionPerformed(evt);
            }
        });
        getContentPane().add(btDel);
        btDel.setBounds(105, 140, 75, 23);

        btSave.setText("Engr");
        btSave.setMinimumSize(new java.awt.Dimension(41, 23));
        btSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSaveActionPerformed(evt);
            }
        });
        getContentPane().add(btSave);
        btSave.setBounds(190, 140, 75, 23);

        btQuit.setText("Quitter");
        btQuit.setMaximumSize(new java.awt.Dimension(41, 23));
        btQuit.setMinimumSize(new java.awt.Dimension(41, 23));
        btQuit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btQuitActionPerformed(evt);
            }
        });
        getContentPane().add(btQuit);
        btQuit.setBounds(275, 140, 69, 23);

        jSeparator1.setBackground(new java.awt.Color(204, 204, 204));
        jSeparator1.setName("seperator1"); // NOI18N
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(10, 170, 340, 10);

        jSeparator2.setBackground(new java.awt.Color(204, 204, 204));
        jSeparator2.setName("seperator1"); // NOI18N
        getContentPane().add(jSeparator2);
        jSeparator2.setBounds(10, 130, 340, 10);

        bt0.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bt0.setText("0");
        bt0.setMinimumSize(new java.awt.Dimension(30, 27));
        bt0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt0ActionPerformed(evt);
            }
        });
        getContentPane().add(bt0);
        bt0.setBounds(90, 285, 75, 40);

        bt1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bt1.setText("1");
        bt1.setMinimumSize(new java.awt.Dimension(30, 27));
        bt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt1ActionPerformed(evt);
            }
        });
        getContentPane().add(bt1);
        bt1.setBounds(20, 180, 75, 40);

        bt2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bt2.setText("2");
        bt2.setMinimumSize(new java.awt.Dimension(30, 27));
        bt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt2ActionPerformed(evt);
            }
        });
        getContentPane().add(bt2);
        bt2.setBounds(90, 180, 75, 40);

        bt3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bt3.setText("3");
        bt3.setMinimumSize(new java.awt.Dimension(30, 27));
        bt3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt3ActionPerformed(evt);
            }
        });
        getContentPane().add(bt3);
        bt3.setBounds(160, 180, 75, 40);

        bt4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bt4.setText("4");
        bt4.setMinimumSize(new java.awt.Dimension(30, 27));
        bt4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt4ActionPerformed(evt);
            }
        });
        getContentPane().add(bt4);
        bt4.setBounds(20, 215, 75, 40);

        bt5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bt5.setText("5");
        bt5.setMinimumSize(new java.awt.Dimension(30, 27));
        bt5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt5ActionPerformed(evt);
            }
        });
        getContentPane().add(bt5);
        bt5.setBounds(90, 215, 75, 40);

        bt6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bt6.setText("6");
        bt6.setMinimumSize(new java.awt.Dimension(30, 27));
        bt6.setName("btPlus"); // NOI18N
        bt6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt6ActionPerformed(evt);
            }
        });
        getContentPane().add(bt6);
        bt6.setBounds(160, 215, 75, 40);

        bt7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bt7.setText("7");
        bt7.setMinimumSize(new java.awt.Dimension(30, 27));
        bt7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt7ActionPerformed(evt);
            }
        });
        getContentPane().add(bt7);
        bt7.setBounds(20, 250, 75, 40);

        bt8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bt8.setText("8");
        bt8.setMinimumSize(new java.awt.Dimension(30, 27));
        bt8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt8ActionPerformed(evt);
            }
        });
        getContentPane().add(bt8);
        bt8.setBounds(90, 250, 75, 40);

        bt9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bt9.setText("9");
        bt9.setMinimumSize(new java.awt.Dimension(30, 27));
        bt9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt9ActionPerformed(evt);
            }
        });
        getContentPane().add(bt9);
        bt9.setBounds(160, 250, 75, 40);

        bt00.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bt00.setText("00");
        bt00.setMinimumSize(new java.awt.Dimension(30, 27));
        bt00.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt00ActionPerformed(evt);
            }
        });
        getContentPane().add(bt00);
        bt00.setBounds(20, 285, 75, 40);

        btrst.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btrst.setText("=");
        btrst.setMinimumSize(new java.awt.Dimension(30, 27));
        btrst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btrstActionPerformed(evt);
            }
        });
        getContentPane().add(btrst);
        btrst.setBounds(160, 285, 75, 40);

        btPlus.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btPlus.setText("+");
        btPlus.setMinimumSize(new java.awt.Dimension(30, 27));
        btPlus.setName("btPlus"); // NOI18N
        btPlus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPlusActionPerformed(evt);
            }
        });
        getContentPane().add(btPlus);
        btPlus.setBounds(230, 180, 115, 40);

        btMinus.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btMinus.setText("-");
        btMinus.setMinimumSize(new java.awt.Dimension(30, 27));
        btMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMinusActionPerformed(evt);
            }
        });
        getContentPane().add(btMinus);
        btMinus.setBounds(230, 215, 115, 40);

        btX.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btX.setText("x");
        btX.setMinimumSize(new java.awt.Dimension(30, 27));
        btX.setName("btPlus"); // NOI18N
        btX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btXActionPerformed(evt);
            }
        });
        getContentPane().add(btX);
        btX.setBounds(230, 250, 115, 40);

        btratio.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btratio.setText("/");
        btratio.setMinimumSize(new java.awt.Dimension(30, 27));
        btratio.setName("btratio"); // NOI18N
        btratio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btratioActionPerformed(evt);
            }
        });
        getContentPane().add(btratio);
        btratio.setBounds(230, 285, 115, 40);

        jLabel1.setBackground(new java.awt.Color(204, 204, 204));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ressources/free-textures.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(4, -6, 360, 470);

        jMenu1.setText("File");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem1.setText("Sauvegarde");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Apropos");

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem2.setText("Developpeur");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    double tab[];
    
    
    private void mainInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mainInputActionPerformed

    private void btSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSaveActionPerformed
        // TODO add your handling code here:
        holder = mainInput.getText();
    }//GEN-LAST:event_btSaveActionPerformed
  
  
    private void btQuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btQuitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btQuitActionPerformed

    private void bt7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt7ActionPerformed
        // TODO add your handling code here:
        String input = mainInput.getText();
         String newInput = "7";
        input += newInput;
        mainInput.setText(input);
    }//GEN-LAST:event_bt7ActionPerformed

    private void bt4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt4ActionPerformed
        // TODO add your handling code here:
        String input = mainInput.getText();
         String newInput = "4";
        input += newInput;
        mainInput.setText(input);
    }//GEN-LAST:event_bt4ActionPerformed

    private void bt8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt8ActionPerformed
        // TODO add your handling code here:
        String input = mainInput.getText();
         String newInput = "8";
        input += newInput;
        mainInput.setText(input);
    }//GEN-LAST:event_bt8ActionPerformed

    private void bt9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt9ActionPerformed
        // TODO add your handling code here:
        String input = mainInput.getText();
         String newInput = "9";
        input += newInput;
        mainInput.setText(input);
    }//GEN-LAST:event_bt9ActionPerformed

    private void bt00ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt00ActionPerformed
        // TODO add your handling code here:
        String input = mainInput.getText();
         String newInput = "00";
        input += newInput;
        mainInput.setText(input);
    }//GEN-LAST:event_bt00ActionPerformed

    private void btrstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btrstActionPerformed
        // TODO add your handling code here:
      Solver sol = new Solver();
      sol.resolve(mainInput);
    }//GEN-LAST:event_btrstActionPerformed

    private void bt0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt0ActionPerformed
        // TODO add your handling code here:
        String input = mainInput.getText();
         String newInput = "0";
        input += newInput;
        mainInput.setText(input);
    }//GEN-LAST:event_bt0ActionPerformed

    private void btClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btClearActionPerformed
        // TODO add your handling code here:
        mainInput.setText("");
        mainInput.requestFocus();
    }//GEN-LAST:event_btClearActionPerformed

    private void btDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDelActionPerformed
        // TODO add your handling code here:
        String input = "";
        input = mainInput.getText();
        if(!input.equals(""))
        mainInput.setText(input.substring(0, input.length()-1));
    }//GEN-LAST:event_btDelActionPerformed

    private void bt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt1ActionPerformed
         String input = mainInput.getText();
         String newInput = "1";
        input += newInput;
        mainInput.setText(input);
        
        
    }//GEN-LAST:event_bt1ActionPerformed

    private void mainInputKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mainInputKeyPressed
        // TODO add your handling code here:
      //JOptionPane.showMessageDialog(this, evt.getKeyChar() , "pp", JOptionPane.INFORMATION_MESSAGE);
      /*String taker ="";
      taker = taker.valueOf(evt.getKeyChar());
      if(!taker.equals("5")){
         String input = "";
        input = mainInput.getText();
        if(!input.equals(""))
        mainInput.setText(input.substring(0, input.length()-1));
      }*/
      
    }//GEN-LAST:event_mainInputKeyPressed

    private void mainInputKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mainInputKeyReleased
        // TODO add your handling code here:
        InputChecker chk1 = new InputChecker();
         Solver sol = new Solver(); // produire le resultat avec la touche entree
        String taker ="";
        int in;
        String setter = mainInput.getText();
        
      
      taker = taker.valueOf(evt.getKeyChar());
      in = evt.getKeyCode();
      //JOptionPane.showMessageDialog(this, in, "Erreur", JOptionPane.ERROR_MESSAGE);
          String a ="";
         
        chk1.checker(mainInput, taker);
          
        switch(in){
             case 8:
                del(mainInput);
                break;
             case 27:
               mainInput.setText("");
                break;
        }
      if(evt.getKeyCode()==10)
      sol.resolve(mainInput);
    }//GEN-LAST:event_mainInputKeyReleased

    private void bt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt2ActionPerformed
        String input = mainInput.getText();
         String newInput = "2";
        input += newInput;
        mainInput.setText(input);
    }//GEN-LAST:event_bt2ActionPerformed

    private void bt3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt3ActionPerformed
        // TODO add your handling code here:
        String input = mainInput.getText();
         String newInput = "3";
        input += newInput;
        mainInput.setText(input);
    }//GEN-LAST:event_bt3ActionPerformed

    private void bt5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt5ActionPerformed
        // TODO add your handling code here:
        String input = mainInput.getText();
         String newInput = "5";
        input += newInput;
        mainInput.setText(input);
    }//GEN-LAST:event_bt5ActionPerformed

    private void bt6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt6ActionPerformed
        // TODO add your handling code here:
        String input = mainInput.getText();
         String newInput = "6";
        input += newInput;
        mainInput.setText(input);
    }//GEN-LAST:event_bt6ActionPerformed

    private void btPlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPlusActionPerformed
        // TODO add your handling code here:
        String input="";
         if(!mainInput.getText().contains("/") && !mainInput.getText().contains("+") && !mainInput.getText().contains("-") && !mainInput.getText().contains("*") && !mainInput.getText().equals("")){
        input = mainInput.getText();
         String newInput = " + ";
        input += newInput;
        mainInput.setText(input);}
    }//GEN-LAST:event_btPlusActionPerformed

    private void btMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMinusActionPerformed
        // TODO add your handling code here:
        String input = mainInput.getText();
         String newInput = " - ";
         if(!mainInput.getText().contains("/") && !mainInput.getText().contains("+") && !mainInput.getText().contains("-") && !mainInput.getText().contains("*")&& !mainInput.getText().equals("") )
        input += newInput;
        mainInput.setText(input);
    }//GEN-LAST:event_btMinusActionPerformed

    private void btXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btXActionPerformed
        // TODO add your handling code here:
        String input = mainInput.getText();
         String newInput = " * ";
         if(!mainInput.getText().contains("/") && !mainInput.getText().contains("+") && !mainInput.getText().contains("-") && !mainInput.getText().contains("*")&& !mainInput.getText().equals(""))
        input += newInput;
        mainInput.setText(input);
    }//GEN-LAST:event_btXActionPerformed

    private void btratioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btratioActionPerformed
        // TODO add your handling code here:
        String input = mainInput.getText();
         String newInput = " / ";
         if(!mainInput.getText().contains("/") && !mainInput.getText().contains("+") && !mainInput.getText().contains("-") && !mainInput.getText().contains("*")&&  !mainInput.getText().equals(""))
        input += newInput;
        mainInput.setText(input);
    }//GEN-LAST:event_btratioActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        String chker = mainInput.getText();
        if(!chker.isEmpty()){
        JOptionPane.showMessageDialog(this, "Le dernier resultat sauvegardé : "+holder, "Sauvegade", JOptionPane.INFORMATION_MESSAGE);
        }else{
            JOptionPane.showMessageDialog(this, "Pas de sauvegarde", "Sauvegade", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Developpée par:Sidiki Camara \nabsicamara@gmail.com \n\n \t Version: 1.0.0");
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    public void del(javax.swing.JTextField a){
        String input = "";
        input = a.getText();
        if(!input.equals(""))
        a.setText(input.substring(0, input.length()-1));
    }
    public void add(javax.swing.JTextField a, String keypad){
         String input = a.getText();
         String newInput = keypad;
        input += newInput;
        a.setText(input);
        if(!input.equals(""))
        a.setText(input.substring(0, input.length()-1));
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Presentation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Presentation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Presentation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Presentation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Presentation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt0;
    private javax.swing.JButton bt00;
    private javax.swing.JButton bt1;
    private javax.swing.JButton bt2;
    private javax.swing.JButton bt3;
    private javax.swing.JButton bt4;
    private javax.swing.JButton bt5;
    private javax.swing.JButton bt6;
    private javax.swing.JButton bt7;
    private javax.swing.JButton bt8;
    private javax.swing.JButton bt9;
    private javax.swing.JButton btClear;
    private javax.swing.JButton btDel;
    private javax.swing.JButton btMinus;
    private javax.swing.JButton btPlus;
    private javax.swing.JButton btQuit;
    private javax.swing.JButton btSave;
    private javax.swing.JButton btX;
    private javax.swing.JButton btratio;
    private javax.swing.JButton btrst;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JOptionPane jOptionPane1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField mainInput;
    // End of variables declaration//GEN-END:variables
}
